openfoodfacts/openfoodfacts-explorer

README.md
=> doc: customize the README

src/routes/+layout.svelte
- Ignore Enter if no query in searchbar (or only whitespaces)
- Disable "Go" button if only whitespaces in searchbar
Fixes #151
:)
=> fix: "Missing query parameter" error on searching empty string

src/routes/+layout.svelte
Add a link to this repos in the form of a button next to settings.
#2
=> feat: Add link to github repo

src/routes/products/search/+page.svelte
Tell the user that no produccts were found instead of showing just a single pagination button with no products. :)
Before:
After:
=> enhancement: Add no products found info on search page

src/routes/products/search/+page.svelte, src/routes/products/search/+page.ts
Fix the broken pagination.
There are only 7 pages for "abc" query, but the pagination section show 50 pages.
Actually, the previous code assumes `page_count` is the total number of pages, but it is actually `Number of products in this page` as obvious from the [API docs](https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v2/#get-/api/v2/search):
The Api return no feild indicting total amount of pages, So this PR calculates the feild `total_pages` and uses it instead of `page_count` :)
Before:
After:
=> fix: Broken pagination

src/lib/api/product.ts, src/lib/const.ts, src/routes/products/[barcode]/edit/+page.svelte, src/routes/products/[barcode]/edit/+page.ts
for each language in the product.languages_codes, show a tab in productnames and indegredients.
Only tabs for available existing languages are show:
- #176 
- #125
=> feat: Add editing support for ingredients and name in all available languages

package.json, pnpm-lock.yaml, src/lib/api/product.ts, src/routes/products/[barcode]/edit/+page.svelte
Add the ability to add a language to a product.   :)
**Notes:**  
- On the main website, adding a language in the editing page does not take effect unless at least one field related to that language is filled. I have modified `src/lib/api/product.ts` to implement the same behavior.  
- On the main website, each language-specific field has an **"Add Language"** button, but adding a language globally (i.e., all language-specific fields receive a new tab for that language). In my implementation, I introduced an **"Add a Language"** button as its own separate card. 
- Either **ISO 639-1** is needed to get a list of all language codes, or we need to hard-code them based on my research.  
- #177
=> feat: allow adding a language to a product

src/routes/products/[barcode]/+page.svelte
The styling of the categories on the product page was just underline and it was feeling a bit clustered and doesn't provide a good user experience
Before
I have changed to the make it more attractive and user friendly
After
Fixes #236
=> changed styling of categories

src/lib/ui/ImageButton.svelte, src/routes/products/[barcode]/+page.svelte
The alignment issues weren't correct on the product page on smaller screens
before (the red colour in background is just for reference)
after
Fixes #230
=> corrected alignment issues

pnpm-lock.yaml, src/lib/knowledgepanels/Panels.svelte
The buttons of environment, health, report a problem in the product page were way too big for the mobile screen 
before
After
Fixes #228
=> style: product page buttons on smaller screen

src/routes/+layout.svelte
Added the GitHub Logo for mobile view in drop down menu
#249 
None
=> Added the GitHub icon in mobile view

src/routes/products/[barcode]/edit/+page.ts
- Qucik PR to increase speed by `await`ing only once and running all requests in parallel.
- Consistently getting half load times.
- Sepcially noticable on slower internets.
Before, About 9s:
After, About 4s:
=> refactor: optimize data fetching with Promise.all for product edit page

src/routes/+layout.svelte
Replaced the camera icon on the header with barcode scanner icon
Desktop view:![Screenshot 2025-03-13 111351](https://github.com/user-attachments/assets/c13f69bc-e7e9-4478-aff8-83f10acfc8e7)
Mobile view:![Screenshot 2025-03-13 111406](https://github.com/user-attachments/assets/8c27a3bc-5105-4269-873d-80afd77b556b)
#255 
#2
=> Replacement of camera icon with barcode scanner icon

src/lib/ui/SmallProductCard.svelte, src/routes/products/[barcode]/+page.svelte
- Clicking the edit button on the product page takes quite a bit of time (over 10s sometimes) and the website feels unresponsive to the user without any loading/progress indication.
- This PR adds loading indication similar to the one presert in `SmallProductCard.svelte`.
- `SmallProductCard.svelte` was using the deprecated version of navigation from `$app/stores`, changed to `$app/state`.
=> enhancement: show loading on edit button

package.json, pnpm-lock.yaml, src/lib/ui/Footer.svelte, static/images/icons/x-logo.svg
Replaced the Twitter older logo with the newer X logo.
The MDI class we use to extract the logos doesn't have the new X-logo, so I created a X-logo.svg in 
``static/images/icons/x-logo.svg``
#265 
None
=> Replaced the twitter logo with X logo

src/routes/+layout.svelte
Added left and right padding to header, making it symmetrical to the footer.
Desktop Header (md+): stays above content with shadow.
Mobile Header (<md): adjusted alignment.
#268 
None
=> feat: added padding to header for symmetrical UI

.env.example, README.md
Updates the `README.md` to include instructions for setting up the `.env` file. Developers can now easily configure their environment by copying `.env.example` and renaming it to ` .env`
1. Added a "Environment Setup" section to README.md
2. Provided a command for copying `.env.example` to `.env
`
#306
=> chore: created `.env.example` for environment variables

.env.example, src/lib/const.ts, src/lib/knowledgepanels/Action.svelte, src/routes/products/search/+page.ts
- Added `VITE_BASE_URL` to `.env.example` with default value `https://world.openfoodfacts.org`
- Updated `src/lib/const.ts` to use this environment variable with a fallback
- Replaced hardcoded URLs in` src/routes/products/search/+page.ts` and `src/lib/knowledgepanels/Action.svelte` to use the API_HOST constant
#331
=> chore: made the base URL configurable via environment variables

.prettierignore, src/routes/products/[barcode]/Prices.svelte
When `prices.results` is undefined, it causes `.length` to throw an error. The error seen in the provided screenshot was: `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')`, and after looking into the stack trace myself, I saw that the error pointed to this line in the component:
I was then able to reproduce the bug locally:
I fixed the bug by using optional chaining to safely access nested properties. This prevents the app from crashing when `prices.results` is undefined and avoids calling `.length` on undefined like before.
With my change, the blank page behaviour wasn't recurring.
#287
=> fix: ...Undefined issue was causing blank screen when launched

src/routes/products/[barcode]/+page.svelte
Fixed the tags text-color's responsiveness as per the theme under categories. 
#389
=> style: fixes the text color of tags in Light mode

src/routes/products/[barcode]/+page.svelte
Earlier the Nova card used to `href="#nutrition_card"` which did not target the specified panel ID.
I've updated here the link to directly target the `href="#nova"` panel ID. This focuses specifically on the Nova food processing classification section when we click it.
#419
=> fix: Nova card not targeting specific panel ID

src/routes/products/[barcode]/+page.svelte, src/routes/products/[barcode]/GreenScore.svelte
- We currently use a grading system which furthers used to map, this console error of `bgColor` arises due to grade being undefined while destructring.
So using a fallback of `( || 'unknown')` for grade whenever it is undefined/null fixes the issue
- Used Crowdin to fix the translations in #406 
Before: blank Screen, as it could not fetch the data from the BE
After: 
#361
=> fix: type errors fixed in a product which fails to fetch

src/routes/products/[barcode]/edit/+page.svelte
- Added a loading spinner when `isSubmitting`(tracks the state variable whether the submit operation is in progress) is true.
- Disabled the button during submission to prevent multiple clicks.
https://github.com/user-attachments/assets/4186e119-a97b-4b0f-9fba-57bab9565d32
#462
=> feat: implementation of loading spinner onclick of Save button (Edit page)

src/routes/products/[barcode]/Folksonomy.svelte
text wrapping issue in folksonomy engine
As the input field does not support text wrapping, so we are gonna toggle between input and textarea fields based on if the user is logged in or not, as the user gets write access if the user is logged in
Fixes #447
=> fix: text-wrapping in folksonomy engine

src/lib/knowledgepanels/Panel.svelte
The contents that can extend on product page looked like normal text fields, so added arrow that will help user know that this content can be extended
Fixes #458
=> fix: added arrows in product page for the content that extends

src/lib/api/prices.ts
_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context._
In this PR, I am fixing issue with open prices auth API. In Open Prices login API, we should be passing value of set_cookie parameter in the query as 1, but currently we are passing value "true", which is incorrect. 
Due to this, Open Prices server is **not returning any cookie** in the headers of the response.
For reference check below code line and the screenshot:
https://github.com/openfoodfacts/open-prices/blob/ada05e3216ea6bca5b92780a2793c170cfd71a58/open_prices/api/auth/views.py#L39
---
- You can request an AI-powered code review by …
=> fix: Fixed value of set_cookie in Open Prices Auth

src/lib/ui/Footer.svelte
footer theme was not correct in light theme
Before (in light theme)
After
Fixes # (issue)
Fixes #487 
Not used
=> fix: corrected the footer colour in light theme

src/routes/folksonomy/+page.svelte
Fixed the content overflow on Folksonomy 
Before
After
Fixes #501 
---
=> fix: fixed content overflow on Folksonomy

src/lib/ui/ImageButton.svelte, src/routes/products/[barcode]/+page.svelte
The container size has been made adaptive for all screens to fit the product image.
Duplicate of #476
Fixes #348 
Before: 
After:
=> fix: product image overflows from the container

src/routes/products/[barcode]/+page.svelte
Added `flex` and `items-center` to ensure proper alignment of content within badges and `break-words` to allow long text to wrap naturally instead of being cut off.
Fixes #489 
---
=> fix: text inside tags getting clipped on mobile browsers

src/routes/products/[barcode]/+page.svelte
The btn's in the product page are overflowing
I tested it by using `join`, but they were still overflowing and also `join` was overwriting the border radius properties
So solved this issue using `flex-wrap`
Fixes #498 
---
=> style: fixed btn's on product page

.github/workflows/semantic-pr.yml
Potential fix for [https://github.com/openfoodfacts/openfoodfacts-explorer/security/code-scanning/3](https://github.com/openfoodfacts/openfoodfacts-explorer/security/code-scanning/3)
To fix the issue, we will add a `permissions` block to the workflow. Since the workflow is validating pull request titles and does not appear to require write access, we will set the permissions to `contents: read` and `pull-requests: read`. This ensures the `GITHUB_TOKEN` has only the minimal permissions necessary for the task.
The `permissions` block will be added at the root level of the workflow, so it applies to all jobs. This is appropriate because the workflow contains only one job (`main`), and there is no indication that additional jobs with different permissions will be added.
---
_Suggested fixes …
=> fix: Potential fix for code scanning alert no. 3: Workflow does not contain permissions

.github/workflows/github-projects.yml
Potential fix for [https://github.com/openfoodfacts/openfoodfacts-explorer/security/code-scanning/2](https://github.com/openfoodfacts/openfoodfacts-explorer/security/code-scanning/2)
To fix the issue, we need to add a `permissions` block to the workflow. This block should specify the minimal permissions required for the workflow to function correctly. Since the workflow interacts with GitHub projects and issues, the permissions should include `contents: read` and `issues: write`. Adding the `permissions` block at the root level of the workflow ensures that all jobs inherit these permissions unless overridden.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> fix: Potential fix for code scanning alert no. 2: Workflow does not contain permissions

src/routes/products/[barcode]/edit/+page.svelte, src/routes/products/[barcode]/edit/+page.ts
Allow viewing the edit page even when not logged, when in vite dev mode, to allow development work without having to configure oauth.
=> fix(dev): allow to view edit page when not logged in

.env.example, src/lib/const.ts, src/routes/+layout.svelte, src/routes/products/[barcode]/+page.svelte, src/routes/products/[barcode]/+page.ts
- Replace broken robotoff integration with the robotoff-contribution-message webcomponent. 
- Add field to off-webcomponents-configuration to enable robotoff component usage.
- Move Matomo fields to constants file
- https://openfoodfacts-explorer-git-robotoff-webcomponent-openfoodfacts.vercel.app/products/5056737900163
=> feat: add robotoff-contribution-message webcomponent to product page

package.json, pnpm-lock.yaml, src/lib/ui/ImageModal.svelte, src/lib/ui/ResizableImage.svelte
- Drop external zoom-image dependency
- Implement ResizableImage and use it in ImageModal
- Improve mobile UX
This drastically simplifies code and uses Svelte native binds and reactivity.
=> feat: implement ResizableImage component

.github/workflows/ci.yml
Potential fix for [https://github.com/openfoodfacts/openfoodfacts-explorer/security/code-scanning/14](https://github.com/openfoodfacts/openfoodfacts-explorer/security/code-scanning/14)
To fix the problem, add an explicit `permissions` block restricting the `contents` permission to `read` at either the workflow root or at each job level. Since none of the jobs or steps modify repository contents, issues, or pull requests, the minimal required permission is `contents: read`. You should edit the `.github/workflows/ci.yml` file and add the following block at the workflow (top) level, right under the workflow name. No additional imports or dependencies are needed. This provides least-privilege for all jobs within the workflow unless jobs specifically override permissions.
_Suggested fixes …
=> ci: add permissions block to ci.yml

src/routes/products/search/+page.svelte
Remove the full screen loading in favor of the shared loading top bar.
Use WcProductCard instead of directly using the product card web-component.
=> fix: remove custom loading display in search page
