openfoodfacts/openfoodfacts-explorer

README.md

- Update README.md with existing features

docs: Update README.md with existing features

---

README.md

- docs: Add links to SDK, Prices and Search

docs: Add links to SDK, Prices and Search

---

src/lib/api/product.ts
src/routes/products/[barcode]/edit/+page.svelte

Allows additions of comments to products edits.
Before:
After:
Comments on main website:
- #164 and one checkbox of #125 
one checkbox of #125

feat: add comments to edits

---

src/routes/folksonomy/+page.svelte
src/routes/settings/+page.svelte

What
Changes the css for settings and folksonomy page's content to help it maintain consistent widths and be responsive towards all screen sezies
Screenshot
Fixes bug(s)
Closes #156

Made the settings and folksonomy page responsive for smaller devices

---

src/lib/api/product.ts
src/routes/products/[barcode]/edit/+page.svelte
src/routes/products/[barcode]/edit/+page.ts

Added store Editing Option in Edit page 
#169 
Additional Info :
formated using pnmp run format .
I would like to add other tag fields editing if the procedures correct !
Looking forward for your feedback .

Added store Editing Option in Edit page

---

src/routes/products/[barcode]/edit/Tags.svelte

This PR fixes the **horizontal overflow issue** in the tag input field by ensuring tags do not extend beyond the container and allowing proper behavior.  
✅ Added `overflow-y-auto` to enable horizontal scrolling  
✅ Ensured the input field remains within the container  
✅ Improved spacing and layout for better UX  
- Closes #190 
[Screencast from 03-03-25 12:52:00 AM IST.webm](https://github.com/user-attachments/assets/ead4996b-0b13-4bd3-aa1b-d40ba1278633)
1. Add multiple tags to the input field.  
2. Ensure they **stay within the container** and scroll horizontally when needed.  
3. Confirm that the input field remains **functional and responsive**.  
> This fix improves usability without introducing breaking changes.

Fix: Resolve Horizontal Overflow Issue (Edit Page)

---

src/lib/ui/ImageModal.svelte
src/routes/products/[barcode]/+page.ts
src/routes/products/[barcode]/Folksonomy.svelte
src/routes/products/[barcode]/Prices.svelte

- Fix 6/15 of the build errors and 1/1 warning. Remaining errors are blocked by openfoodfacts/open-prices#742
- #202

chore: fix some `pnpm check` errors and warning

---

src/lib/api/folksonomy.ts

What
Fixes the token not being correctly parsed in the login method.
Fixes bug(s)
#171

Fix: fixed the token error in login

---

src/lib/api/product.ts
src/lib/api/taxonomy/types.ts
src/routes/products/[barcode]/+page.svelte
src/routes/products/[barcode]/+page.ts
src/routes/products/[barcode]/edit/+page.svelte
src/routes/products/[barcode]/edit/+page.ts

Added Origins and Countries  in the details section and also implemented editing for origins and countries.
#169
#173 
Looking forward for your feedback! Except for tracebility codes , tag fields editing is completed .Can I know what are tracebility codes?

TagFieldEditing

---

src/lib/nutriscore/NutriScore.svelte
src/routes/products/[barcode]/+page.svelte

What
This fixes the working of nutriscore and greenScore buttons on products page.
Fixes bug(s)
#221

fix: nutriscore and greenscore links in product page

---

src/lib/api/prices.d.ts
src/lib/api/prices.ts

- 
- integrated open price data API
- 
- #51
-

chore: update open price data bindings

---

src/routes/settings/Influence.svelte

Added a meter that shows the current percentage value of slider.
- #251 
None

Added the current percentage value of slider in Influence component

---

src/lib/ui/Footer.svelte
src/routes/+layout.svelte
src/routes/+page.svelte

Implemented the footer as per the issue #256 
You can let me know if you want any changes
Fixes #256

feat: add global footer

---

src/lib/knowledgepanels/Panel.svelte
src/lib/knowledgepanels/PanelGroup.svelte
src/routes/products/[barcode]/+page.svelte
src/routes/products/[barcode]/GS1Country.svelte
src/routes/taxo/[taxo]/[id]/+page.svelte

decrease font size for smaller screens

---

src/routes/+error.svelte
src/routes/+layout.svelte
src/routes/folksonomy/[key]/+page.svelte
src/routes/products/[barcode]/edit/+page.svelte
src/routes/products/search/+page.svelte
src/routes/taxo/[taxo]/[id]/+page.svelte

Migrate the use of Svelte v4 `run` and`$page` import to v5.

migrate: run & page import

---

src/routes/settings/+page.svelte

Enhanced login functionality with:
- **Visual Feedback**: Loading spinner, success/error alerts, fade transitions, auto-clearing messages.
- **Auth State Management**: Checks login status, toggles UI states, clears credentials on logout.
- **Accessibility Fixes**: Improved labels, proper text styling, added button ID.
- **User Experience**: Clear login status, field reset on logout, disabled button during auth.
https://github.com/user-attachments/assets/9b194dd6-a0ed-445c-b1dd-f5a371628ac9
#93 
None

feat: enhancements for authentication

---

src/lib/api/product.ts
src/routes/products/[barcode]/edit/+page.svelte

1. Added new fields to the edit form:
- EMB code (Producer code)
- Packaging information
- Manufacturing places
- Serving size
2. Added a comprehensive nutritional information editing section that allows users to edit:
- Energy values (kJ and kcal)
- Fat and saturated fat
- Carbohydrates and sugars
- Proteins
- Salt and sodium
3. Updated the Product type definition to include the new fields
4. Updated the API submission method to include these new fields when saving the product
https://github.com/user-attachments/assets/af47b591-a98f-4679-957b-e5fc7b140258
#168 
#170 
#114 
#125

feat: implementation of product basic editing, packaging editing and nutritional information editing

---

src/lib/ui/ImageButton.svelte
src/lib/ui/ImageModal.svelte

In both components:
- Added rotation state and 90-degree rotate function.
- Restricted to logged-in users via preferences store.
- Applied smooth CSS rotation animation.
In ImageButton.svelte:
- Small, semi-transparent circular rotate button in bottom-right, solid on hover, for logged-in users only.
In ImageModal.svelte:
- Larger, semi-transparent circular rotate button in bottom-right, solid on hover, for logged-in users only.
- Resets rotation on modal open/close.
https://github.com/user-attachments/assets/b933aabf-14c1-4b69-a638-34d7f3a9c99a
#181

feat: implementation of rotation of images for logged in users

---

src/lib/greenscore/GreenScore.svelte
src/lib/nova/Nova.svelte
src/lib/nutriscore/NutriScore.svelte
src/routes/products/[barcode]/+page.svelte

Fixes #237 
Changed the preference section of the product page
Before
After

preference section on product page

---

.github/labeler.yml
.github/workflows/ci.yml
.husky/pre-commit
package.json
pnpm-lock.yaml

1. Added `pnpm format` step to CI workflow (`.github/workflows/ci.yml`)
2. Set up pre-commit hook:
- Added husky as dev dependency
- Added prepare and `pre-commit` scripts to `package.json`
- Created  `.husky/pre-commit` hook to run `pnpm format`
3. Fixed the broken CI in `labeler.yml` which caused commit issues
#323

ci: setup of pre-commit hook for pnpm format and added pnpm format job to CI/CD pipeline

---

src/lib/knowledgepanels/Map.svelte

- Validated map pointers for correct latitude/longitude.
- Added error handling for marker creation and map setup.
- Ensured cleanup on unmount with proper marker tracking.
- Used `bind:this` for direct map container reference.
- Fixed async code in `onMount`.
These changes prevent marker issues by validating data, handling errors, and avoiding leaks.
#239

fix: location marker gets broken on map

---

.github/labeler.yml

- ci: labeler for off-explorer

ci: labeler for off-explorer

---

src/routes/folksonomy/+page.svelte

- Upgraded Visuals: Added a sleek header with subtitle, switched to a card-based layout, and included progress bars, colored badges, hover animations, and a responsive grid with smooth transitions.
- Better Structure: Keys are auto-grouped by prefix, collapsible for less clutter, and feature usage badges with a clear visual hierarchy.
- New Features: Introduced a search box with result counter, empty state message, and usage progress bars.
- Tech Enhancements: Built with Svelte’s reactive variables, optimized rendering, and accessible, responsive design.
https://github.com/user-attachments/assets/bd0f7e6b-0319-4012-b936-a82f33fb0f33
#260 #315 
#2

feat: beautification of Folksonomy engine key (/folksonomy)

---

src/lib/api/prices.ts
src/routes/products/[barcode]/Prices.svelte

All errors have been fixed while running `pnpm check`
#300 
None

chore: fixed all errors in `pnpm check`

---

src/lib/ui/SmallProductCard.svelte
static/Placeholder.svg

- 
- Handled missing images in cards on the home page
-
Before:
After:
- 
#272 
- 
#272 (Handled missing images issue)

handle missing images in home page cards (#272)

---

.devcontainer/devcontainer.json

To facilitate easier development this PR adds a devcontainer. This allows to quickly spin up a development environment without the need for a local deployment. Try it by clicking the <> Code button and creating a new Codespace.

feat:add devcontainer.json

---

src/routes/products/[barcode]/Prices.svelte

chore: fixed the last `pnpm check` error

---

.github/workflows/github-projects.yml
.github/workflows/semantic-pr.yml

ci: force Pull Requests to be semantic

---

src/lib/ui/SmallProductCard.svelte

- Corrected the path of Placeholder.svg in the SmallProductCard component to ensure it loads properly during product search.
Before:
After:
- #373 
- #373

Corrected the path of Placeholder.svg in the SmallProductCard component

---

src/routes/products/[barcode]/+page.svelte

Added share button on product page
Fixes #382

feat: add share button on product page

---

README.md

docs: README additions

---

src/lib/ui/SmallProductCard.svelte
src/routes/+page.svelte

I tried to use the minimal amount of absolute values in classes, while keeping it responsive to all screens.
Everyone are invited to share their valuable suggestions and insights. 
1.![Screenshot 2025-04-09 171520](https://github.com/user-attachments/assets/a0c7e975-524f-4058-ad32-1c3b43e2e792)
2. 
3. 
#426

style: fixed the inconsistency of UI in landing page

---

.github/.gemini/config.yaml
.github/pull_request_template.md

- Run Gemini code review only on demand
- Add PR template

fix: Update PR pipeline

---

src/routes/products/[barcode]/edit/Tags.svelte

fix: overlapping tags in edit page

---

src/lib/ui/SmallProductCard.svelte

Fixed alignment issues in product card on smaller devices
Before
After
Fixes #494 
**LLM Usage Disclosure:** not used

fix: fixed alignment issues in product card on smaller screens

---

src/routes/+layout.svelte
src/routes/+page.svelte

- The header was not responsive on smaller screens
- 'Welcome to OFF' has double padding
Before
After
https://github.com/user-attachments/assets/d4ac6369-1362-4573-92e2-57eaf94a379a
Fixes #496 
---
**LLM Usage Disclosure:** not used

fix: fixed header issues on smaller screens

---

src/lib/i18n/index.ts
src/routes/+layout.svelte

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context._
This PR resolves issue  by implementing a graceful fallback to the default English locale when the requested localization file fails to load (e.g., due to network issues). It introduces an `isLoading` state within the i18n setup to ensure the frontend does not render content until the localization resources have fully loaded, thereby preventing crashes related to the `svelte-i18n` library.
**Changes:**
- Implemented `isLoading` state to handle asynchronous loading of locale files gracefully.
Fixes #510
- You can request an AI-powered code …

fix: fallback locale and isLoading for i18n crash on offline 

---

src/routes/products/search/+page.ts

Currently in the search, it only checks if the barcode is 13 digits long or not, and not if it is EAN13 code or not
Implemented the function to check if the barcode is EAN13 code or not, if it is then only it will redirect to the product page 
Fixes #512 

feat: implemented function to check if given barcode is EAN13 code or not

---

src/lib/i18n/messages/en.json
src/lib/i18n/messages/it.json
src/lib/ui/Navbar.svelte
src/routes/+layout.svelte

Implemented a navbar for quick navigation to important pages. The navbar includes links to the below pages:
- Discover (yet to be implemented)
- Contribute (yet to be implemented)
- Producers (yet to be implemented)
- Prices (yet to be implemented)
- Folksonomy (already implemented)
https://github.com/user-attachments/assets/fd8d988a-1608-4062-bfbf-04c1eead8a36
- You can request an AI-powered code review by commenting `/gemini review` on this PR after it's been created.
Part of:
https://github.com/openfoodfacts/openfoodfacts-explorer/issues/530

feat: Implemented Navbar for explorer

---

package.json
pnpm-lock.yaml
src/global.d.ts
src/routes/+layout.svelte
src/routes/+page.svelte
vite.config.ts

Added the Donation Banner Web component in the explorer homepage.
Fixes # (issue)
- #533  
---
- You can request an AI-powered code review by commenting `/gemini review` on this PR after it's been created.

feat: Added Donation banner web component

---

src/routes/+layout.svelte
src/routes/settings/+page.svelte

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context._
Fixes #582 
---

chore: move GitHub link from navbar to settings page 

---

src/lib/ui/SearchBar.svelte
src/routes/+layout.svelte

- Add a loading indication while we search for products
- Add a loading indication while we search for completions

feat: add "searching" and "loading" state to SearchBar component

---

package.json
pnpm-lock.yaml
src/lib/api/search.ts
src/lib/i18n/messages/en.json
src/lib/ui/VegaChart.svelte
src/routes/products/search/+page.svelte
src/routes/products/search/+page.ts
svelte.config.js

Implemented vega chart from the search results.
Fixes # (issue)
---
- You can request an AI-powered code review by commenting `/gemini review` on this PR after it's been created.

feat: Added charts for the search results

---

src/lib/api/search.ts
src/lib/i18n/messages/en.json
src/routes/products/search/+page.svelte
src/routes/products/search/+page.ts

    feat: add price display to product search results

---

src/lib/ui/Footer.svelte

Simplify badges and images handling
Fixes #634

feat: swap the links in the footer to our own static serving

---

svelte.config.js

fix: allow Wikimedia images in CSP

---

src/lib/i18n/messages/en.json
src/routes/facets/[facet]/+page.svelte
src/routes/facets/[facet]/[value]/+page.svelte

feat: add navigation links for facets and improve i18n support

---

src/lib/i18n/messages/en.json
src/lib/ui/WcProductCard.svelte
src/routes/facets/[facet]/[value]/+page.svelte
src/routes/facets/[facet]/[value]/+page.ts
src/routes/products/[barcode]/DataSources.svelte
src/routes/users/[user]/+page.svelte
src/routes/users/[user]/+page.ts

- Implement user pages
https://openfoodfacts-explorer-git-user-page-openfoodfacts.vercel.app/users/vaiton

feat: user page

---

src/lib/api/folksonomy.ts
src/routes/products/[barcode]/+page.svelte
src/routes/products/[barcode]/+page.ts
src/routes/products/[barcode]/Folksonomy.svelte

TODO
- Integrate as an option the webcomponent folksonomy editor
---

feat: enhance Folksonomy integration with new editor and value fetching

---

src/routes/products/[barcode]/ProductHeader.svelte

feat: add traceability codes links in ProductHeader

---

src/lib/i18n/messages/en.json
src/routes/+page.svelte

feat: add landing page with project overview and navigation options

---

src/lib/api/product.ts
src/lib/ui/images/PhotoTypeSection.svelte

Related to https://github.com/openfoodfacts/openfoodfacts-explorer/issues/270

fix: use sdk for API v3 image upload

---

src/lib/ui/EditProductForm.svelte
src/lib/ui/InfoTooltip.svelte

fix(ui): adjust tooltip position in InfoTooltip component

---

src/lib/i18n/messages/en-US.json
src/lib/ui/edit-product-steps/ImagesStep.svelte

feat: add legal warnings for photo copyright in ImagesStep component

---

src/routes/+layout.svelte
src/routes/products/[barcode]/+page.svelte

fix: only display NutritionCalculator component on product pages

---

src/lib/knowledgepanels/Panel.svelte

fix: remove unnecessary horizontal rule in element list rendering

---

src/lib/knowledgepanels/Element.svelte
src/lib/knowledgepanels/Panel.svelte
src/lib/knowledgepanels/PanelGroup.svelte
src/lib/knowledgepanels/Panels.svelte
src/lib/knowledgepanels/Table.svelte
src/lib/knowledgepanels/TextElement.svelte

- Extract Table into its own component
- Improve TextElement styling based on different KP properties
- Add Panel styling for average evaluations

feat: improve KP handling

---

src/lib/i18n/messages/en-US.json
src/routes/products/[barcode]/DataSources.svelte

feat: enhance data source display

---

package.json
pnpm-lock.yaml
src/routes/+layout.svelte
src/routes/Shortcuts.svelte
src/routes/products/[barcode]/+page.svelte
src/routes/products/[barcode]/ProductAttributes.svelte

 feat: implement barcode display in product page

---

src/lib/ui/edit-product-steps/NutritionStep.svelte

feat(nutrition): add button to swap energy units between kj and kcal

---

src/lib/api/product.ts
src/lib/ui/images/PhotoManager.svelte
src/lib/ui/images/PhotoTypeSection.svelte
src/routes/products/[barcode]/edit/+page.svelte

feat(images): enhance image display with uploader info and upload timestamp
